/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:5156fa54-0a14-4a35-8938-d95ed34498d6",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_O4hhaJUFO",
    "aws_user_pools_web_client_id": "10rhq288q07h9ud02obc9b53ge",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "polls",
            "endpoint": "https://zm1cwduje0.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "pollking55467a93b2f34bbcbac5cc2da4cc1718160041-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
